### ISSUE TITLE
 [Errno 2] No such file or directory: 'big.model'`

### ISSUE THREAD

**Issue by meet-VC** [domanchi/gibberish-detector#2]
I tried installing the library using command

``
pip install gibberish-detector
``

Python Version: 3.7.5

While adding following commands:

```
from gibberish_detector import detector
Detector = detector.create_from_model('big.model')
```
I am receiving error like:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/meet/Desktop/sms_chatbot/3.7/env/lib/python3.7/site-packages/gibberish_detector/detector.py", line 11, in create_from_model
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'big.model'`

**Comment by domanchi** [comment]
I'm confused. Did you first create a model, as described in the example? https://github.com/domanchi/gibberish-detector#examples

**Comment by rooterkyberian** [comment]
it would be nice to prepackage it or at very least allow it to be trained using couple lines of python code (including dataset download since probably adding ~7MB to package is not a best idea)

**Comment by meet-VC** [comment]
> 
> 
> I'm confused. Did you first create a model, as described in the example? https://github.com/domanchi/gibberish-detector#examples

Sorry, it was my mistake. I didn't create the model, once created it works perfectly.

**Comment by meet-VC** [comment]
Sorry, it was my mistake. I didn't create the model, once created it works perfectly.
