### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by PeggyFan** [domanchi/gibberish-detector#6]
I tried running the code by importing the module:

```
from gibberish_detector import detector
Detector = detector.create_from_model('big.model')
print(Detector.is_gibberish('ertrjiloifdfyyoiu'))
```
but it says 
`FileNotFoundError: [Errno 2] No such file or directory: 'big.model'`

what is missing here?

**Comment by domanchi** [comment]
You need to first create the `big.model` file. Check out the examples for how to train this model: https://github.com/domanchi/gibberish-detector#examples
